#!/bin/bash

# set python version
source venv/bin/activate;

crawl() {
  echo "========= Starting $1 crawl =========="
  scrapy crawl $1 | tee -a "crawl-$1.log";
}

crawl yoti
crawl sailboatlistings
crawl yachthub

echo =================== ALL DONE ====================
